from flask_sqlalchemy import SQLAlchemy

#create an SQLAlchemy object
db = SQLAlchemy()

#Define model
class Students(db.Model):
    #If a model does not set __tablename__, it will be generated by converting the class name from CamelCase to snake_case
    # __tablename__ = 'students'

    id = db.Column(db.Integer, primary_key=True)
    name=db.Column(db.String)
    email=db.Column(db.String)

    #representation method - used to define how objects should be represented when printed
    def __repr__(self):
        return f"Student: {self.name} {self.email}"